plugins {
    id 'net.neoforged.gradle.userdev' version '7.1.4'
    id 'java-library'
    id 'maven-publish'
}

group = library_group
version = library_version
def library_artifact_id = project.findProperty("library_artifact") ?: "material-lib"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly "net.neoforged:neoforge:21.11.33-beta"
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
}

test {
    useJUnitPlatform()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = group
            artifactId = library_artifact_id
            version = version

            from components.java
        }
    }

    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/theelementguy/material-lib")

            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
                password = project.findProperty("gpr.key") ?: System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}